/* This file is automatically generated from a *.form file. Do not modify it manually. */

angular.module('page', []);
angular.module('page')
.factory('httpRequestInterceptor', function () {
	var csrfToken = null;
	return {
		request: function (config) {
			config.headers['X-Requested-With'] = 'Fetch';
			config.headers['X-CSRF-Token'] = csrfToken ? csrfToken : 'Fetch';
			return config;
		},
		response: function(response) {
			var token = response.headers()['x-csrf-token'];
			if (token) {
				csrfToken = token;
			}
			return response;
		}
	};
})
.config(['$httpProvider', function($httpProvider) {
	$httpProvider.interceptors.push('httpRequestInterceptor');
}])
.controller('PageController', function ($scope, $http) {

		require(['handlers/myhandler.js'], function(myhandler){
			$scope.myhandler = new myhandler();
		});

    
        $http.get("feeds/student.json")
            .success(function(data) {
                $scope.data = data;
            });
    
        $http.get("feeds/countries.json")
            .success(function(data) {
                $scope["countries"] = data;
            });

        $scope.embeddedCallback = function(event)
        {
             // callback code
            alert(event.target.innerHTML + ' clicked.');}
        $scope.scriptCall = function(event)
        {
             // callback code
            myScriptFunction();
        }
        $scope.handlerCall = function(event)
        {
             // callback code
            $scope.myhandler.myHandlerFunction();
        }

});